# Generated by Django 4.2.5 on 2023-09-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='current_version_indicator',
            new_name='is_active',
        ),
    ]
